name: "CarToolForge Quality Gate"

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: "Run BuildSrc Spotless"
        run: ./gradlew :buildSrc:spotlessCheck --no-daemon

      - name: "Run BuildSrc unit tests"
        run: ./gradlew :buildSrc:test --info --no-daemon

      - name: "Build and test application"
        run: ./gradlew clean build --info --no-daemon

      - name: "Upload reports"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-and-test-reports
          path: |
            **/build/reports/*
          retention-days: 30
